name: firebase_auth2
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
 sdk: '>=3.4.0 <4.0.0'


dependencies:
 flutter:
   sdk: flutter
 cupertino_icons: ^1.0.6
 firebase_core: ^2.31.1
 firebase_auth: ^4.19.5
 cloud_firestore: ^4.17.4
 path_provider: ^2.1.3
 email_otp: ^2.1.2
 pin_code_fields: ^8.0.1
 google_sign_in: ^6.2.1
 firebase_crashlytics: ^3.5.6
 firebase_analytics: ^10.10.6



dev_dependencies:
 flutter_test:
   sdk: flutter
 flutter_lints: ^3.0.0



flutter:
 uses-material-design: true