// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6lhrGZoUQG0iyK4_r9szLiLtcLnTeesU',
    appId: '1:392049355028:android:a95b8428385639b5dc7a01',
    messagingSenderId: '392049355028',
    projectId: 'auth-fire2',
    storageBucket: 'auth-fire2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdFpOT8sHb2uw8C1u8f_SDhsZhNAYOo7I',
    appId: '1:392049355028:ios:5974e7adc6defb8fdc7a01',
    messagingSenderId: '392049355028',
    projectId: 'auth-fire2',
    storageBucket: 'auth-fire2.appspot.com',
    androidClientId: '392049355028-op2q667t0m69nmf2rosdd8201rm7mmgc.apps.googleusercontent.com',
    iosClientId: '392049355028-4mm1k676vcij0p97u4o3felsrj9u145g.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth2',
  );

}